name = "emit"
version = "0.0.1"
description = "A simple event sourcing library for gleam!"
gleam = ">= 1.0.0"
licences = ["Apache-2.0"]
target = "erlang"
repository = { type = "github", user = "DominikBB", repo = "emit" }

[dependencies]
gleam_stdlib = ">= 0.39.0 and < 1.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_otp = "~> 0.10"

[dev-dependencies]
gleeunit = "~> 1.0"
youid = ">= 1.2.0 and < 2.0.0"
prng = ">= 3.0.3 and < 4.0.0"

#[documentation]
#pages = [
  #{ title = "Event sourcing 101", path = "event-sourcing-101.html", source = "./pages/event-sourcing-101.md" },
  #{ title = "How emit works", path = "how-emit-works.html", source = "./pages/how-emit-works.md" },
  #{ title = "Get started with emit", path = "get-started-with-emit.html", source = "./pages/get-started-with-emit.md" },
#]