name = "signal"
version = "0.2.2"
description = "A simple event sourcing library for gleam!"
gleam = ">= 1.0.0"
licenses = ["Apache-2.0"]
target = "erlang"
repository = { type = "github", user = "DominikBB", repo = "signal" }

[dependencies]
gleam_stdlib = ">= 0.39.0 and < 1.0.0"
gleam_erlang = ">= 0.25.0 and < 2.0.0"
gleam_otp = "~> 0.10"

[dev-dependencies]
gleeunit = "~> 1.0"
youid = ">= 1.2.0 and < 2.0.0"
prng = ">= 3.0.3 and < 4.0.0"

  #{ title = "Event sourcing 101", path = "event-sourcing-101.html", source = "./pages/event-sourcing-101.md" },
  #{ title = "Get started with signal", path = "get-started-with-signal.html", source = "./pages/get-started-with-signal.md" },
[documentation]
pages = [
  { title = "How signal works", path = "how-signal-works.html", source = "./pages/how-signal-works.md" },
]