name = "emit"
version = "0.0.1"

[dependencies]
gleam_stdlib = ">= 0.39.0 and < 1.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
gleam_otp = "~> 0.10"
youid = ">= 1.2.0 and < 2.0.0"
mumu = ">= 1.0.3 and < 2.0.0"
prng = ">= 3.0.3 and < 4.0.0"
