name = "cart"
version = "1.0.0"

target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 0.16.0 and < 1.0.0"
emit = { path = "../.." }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
