name: test signal

on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: erlef/setup-beam@v1
              with:
                  otp-version: '26.0.2'
                  gleam-version: '1.4.0'
                  rebar3-version: '3'
            - run: gleam format --check src test
            - run: gleam deps download
            - run: gleam test
            - run: gleam format --check src test

            - name: Enable PostgreSQL
              run: sudo systemctl start postgresql.service

            - name: Create a database
              run: sudo createdb -u postgres signal_dev

            - name: Signal PGO tests
              run: gleam test
              working-directory: extensions/signal_pgo
